spring.application.name=jobapp1
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.generate-ddl=true
#shows the sql queries used
spring.jpa.show-sql=true
#it will recreate the tables on every start of the application(used in testing env)
spring.jpa.hibernate.ddl-auto=create-drop